---
# This will install elastic search
    - copy: src=/home/zbo/Downloads/elasticsearch-2.3.3.rpm dest=/home/vagrant/InstallSave/ELK
    - name: rpm install elastic search
      sudo: yes
      yum: name=/home/vagrant/InstallSave/ELK/elasticsearch-2.3.3.rpm state=present
    - name: create config dir
      sudo: yes
      file: path=/usr/share/elasticsearch/config state=directory

    - name: chmod elastic
      sudo: yes
      shell: chmod -R 777 /usr/share/elasticsearch

    - name: install head plugin
      sudo: yes
      unarchive: src=head.tar.gz dest=/usr/share/elasticsearch/plugins

    - unarchive: src=/home/zbo/Downloads/kibana-4.5.1-linux-x64.tar.gz dest=/home/vagrant/InstallSave/ELK
    - template: src=kibana.yml dest=/home/vagrant/InstallSave/ELK/kibana-4.5.1-linux-x64/config/

    - unarchive: src=/home/zbo/Downloads/elasticsearch-2.3.3.tar.gz dest=/home/vagrant/
    - template: src=elasticsearch.yml dest=/home/vagrant/elasticsearch-2.3.3/config/

    - file: path=/home/vagrant/elasticsearch-2.3.3/plugins state=directory
    - unarchive: src=head.tar.gz dest=/home/vagrant/elasticsearch-2.3.3/plugins

    - copy: src=kill-e.sh dest=/home/vagrant/kill-e.sh
    - copy: src=start-e.sh dest=/home/vagrant/start-e.sh
    - shell: sh /home/vagrant/kill-e.sh
    - shell: sh /home/vagrant/start-e.sh

    - copy: src=kill-k.sh dest=/home/vagrant/kill-k.sh
    - copy: src=start-k.sh dest=/home/vagrant/start-k.sh
    - shell: sh /home/vagrant/kill-k.sh
    - shell: sh /home/vagrant/start-k.sh
