---
- hosts: vag
  remote_user: vagrant
  tasks:
    - name: make sure folder exists
      file: path=/home/vagrant/InstallSave/ELK state=directory

    - name: copy java
      copy: src=/Users/twer/project/Software/jdk-7u17-linux-x64.rpm dest=/home/vagrant/InstallSave/ELK

    - name: copy elastic search
      copy: src=/Users/twer/project/Software/elasticsearch-1.5.2.noarch.rpm dest=/home/vagrant/InstallSave/ELK

    - name: rpm install java
      sudo: yes
      yum: name=/home/vagrant/InstallSave/ELK/jdk-7u17-linux-x64.rpm state=present

    - name: rpm install elastic search
      sudo: yes
      yum: name=/home/vagrant/InstallSave/ELK/elasticsearch-1.5.2.noarch.rpm state=present

    - name: make sure logstash folder exists
      file: path=/home/vagrant/InstallSave/ELK/Logstash state=directory

    - name: copy logstash
      unarchive: src=/Users/twer/project/Software/logstash-1.4.2.tar.gz dest=/home/vagrant/InstallSave/ELK/Logstash

    - name: make sure kibana folder exists
      file: path=/home/vagrant/InstallSave/ELK/kibana state=directory

    - name: copy kibana
      unarchive: src=/Users/twer/project/Software/kibana.zip dest=/home/vagrant/InstallSave/ELK/Kibana


#    - name: make sure folder exists
#      sudo: yes
#      file: path=/etc/haproxy state=directory
#
#    - name: unarchive haproxy tar.gz
#      unarchive: src=/Users/twer/project/Software/haproxy-1.4.17.tar.gz dest=/home/vagrant/InstallSave/Haproxy
#
#    - name: copy make install script
#      copy: src=./makeinstall.sh dest=/home/vagrant/InstallSave/Haproxy
#
#    - name: make install binary
#      sudo: yes
#      shell: cd /home/vagrant/InstallSave/Haproxy && sh makeinstall.sh
#
#    - name: copy init.d script for haproxy service
#      sudo: yes
#      copy: src=./haproxy dest=/etc/init.d
#
#    - name: make service 755
#      sudo: yes
#      shell: chmod 755 /etc/init.d/haproxy
#
#    - name: copy conf file
#      sudo: yes
#      copy: src=./haproxy.cfg dest=/etc/haproxy
#
#    - name: copy sbin from install folder to exe sbin
#      sudo: yes
#      shell: cp /usr/local/haproxy14/sbin/haproxy /usr/local/sbin/
#
#    - name: start haproxy service
#      sudo: yes
#      service: name=haproxy state=started enabled=true

